# Executed for:
# - [no] Interactive Shells
# - [yes] The Login Shell
# - [no] Shell Scripts

# Order:
# zshenv - zprofile - zshrc - zlogin

if type "archey3" > /dev/null 2>&1
then
    archey3 -c yellow
fi