# Executed for:
# - [yes] Interactive Shells
# - [yes] The Login Shell
# - [yes] Shell Scripts

# Order:
# zshenv - zprofile - zshrc - zlogin

export EDITOR=nvim

# Pager
if type "nvimpager" > /dev/null 2>&1
then
    export PAGER="nvimpager"
    alias less=$PAGER
    alias more=$PAGER 
    export MANPAGER="nvimpager"
fi

# For Nim
if [ -d ${HOME}/.nimble/bin ]
then
    export PATH=${HOME}/.nimble/bin:${PATH}
fi

