# Lang
# [[plugins]] # Haml
# repo  = 'tpope/vim-haml'
# on_ft = 'haml'

#[[plugins]] # zsh
#repo = 'zchee/deoplete-zsh'
#on_ft = 'zsh'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # TPTP
repo  = 'c-cube/vim-tptp'
on_ft = 'tptp'

[[plugins]] # Prolog
repo = 'soli/prolog-vim'
on_ft = 'prolog'

[[plugins]] # Haskell syntax
repo  = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'

[[plugins]] # Haskell type checker
repo  = 'parsonsmatt/intero-neovim'
on_ft = 'haskell'
hook_post_source = '''
	nmap <silent> <buffer> <LocalLeader>gt <Plug>InteroGenericType
	nmap <silent> <buffer> <LocalLeader>t <Plug>InteroType

	nmap <silent> <buffer> <LocalLeader>bs :InteroStart<CR>
	nmap <silent> <buffer> <LocalLeader>bk :InteroKill<CR>
	nmap <silent> <buffer> <LocalLeader>br :InteroRestart<CR>

	nmap <silent> <buffer> <LocalLeader>o :InteroOpen<CR>
	nmap <silent> <buffer> <LocalLeader>c :InteroHide<CR>

	nmap <silent> <buffer> <LocalLeader>l :InteroLoadCurrentFile<CR>
'''

[[plugins]] # Haskell completion
repo = 'eagletmt/neco-ghc'
on_ft = 'haskell'
hook_source = '''
	au User CmSetup call cm#register_source({'name' : 'neco-ghc',
		\ 'abbreviation': 'hs', 
		\ 'priority': 9, 
		\ 'scoping' : 1,
		\ 'scopes' : ['haskell'],
		\ 'cm_refresh_patterns': ['.'],
		\ 'cm_refresh': {'omnifunc' : 'necoghc#omnifunc'}
		\ })
'''

#[[plugins]] # Python
#repo = 'davidhalter/jedi-vim'
#on_ft = ['python', 'python3']
#hook_source = '''
#let g:jedi#auto_initialization = 1 
#let g:jedi#completions_command = ""
#'''
#[[plugins]]
#repo = 'zchee/deoplete-jedi'
#on_ft = ['python', 'python3']

[[plugins]] # Python
repo = 'wmayner/python3-syntax'
on_ft = ['python']
hook_source = '''
	let python_highlight_all = 1
'''

[[plugins]] # Markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_source = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
'''

#[[plugins]] # Vim Script
#repo = 'Shougo/neco-vim'
#on_ft = 'vim'

[[plugins]] # TeX
repo  = 'lervag/vimtex'
on_ft = ['tex', 'plaintex', 'context']
hook_add = '''
	 let g:tex_flavor = "latex"
'''
hook_source = '''
	let g:vimtex_latexmk_options = '-pdf -pdflatex="luajittex --fmt=luajitlatex.fmt"'

	" NCM completion
	au User CmSetup call cm#register_source({'name' : 'vimtex',
			\ 'priority': 9, 
			\ 'scoping': 1,
			\ 'scopes': ['latex'],
			\ 'abbreviation': 'latex',
			\ 'cm_refresh_patterns': ['\'],
			\ 'cm_refresh': {'omnifunc': 'vimtex#complete#omnifunc'},
			\ })
	let g:vimtex_complete_close_braces = 1

	let g:vimtex_format_enabled = 1

	let g:vimtex_index_hide_line_numbers = 0
	let g:vimtex_imaps_enabled = 0
	let g:vimtex_fold_enabled = 0
'''
hook_post_source = '''
	" unmap <buffer> tsd
	" unmap <buffer> tse
	nmap <buffer> <LocalLeader>l* <plug>(vimtex-env-toggle-star)
	nmap <buffer> <LocalLeader>lp <plug>(vimtex-delim-toggle-modifier)

	setlocal noexpandtab	
	setlocal tabstop=2
	setlocal shiftwidth=2
	setlocal softtabstop=2
	setlocal autoindent
'''

[[plugins]] # Penn Treebank, NPCMJ
repo = 'aslemen/penn.vim'
on_ft = ['penn']

[[plugins]]
repo = 'aslemen/Keyaki.vim'
on_ft = ['penn']
